### PR TITLE
fix: Rectify all tests with atleast 70% coverage

### LINKED ISSUE #48: fix: Implement proper tests for internal/cli/command/config/config_test.go
Description:

These tests are failing because of the recent changes in code structure. It is needed to be given due diligence.

Present Behaviour:

The present tests are failing.

Expected Behaviour:

Implement proper tests

### LINKED ISSUE #49: fix: Add tests for internal/executor package
Description:

The present logic does not implement tests for the execution code.

Present Behaviour:

No tests present

Expected Behaviour:

Tests should be added.

### PR DESCRIPTION
**Pull request by littlestar642**
Description:

Due to recent changes in the folder structure and development strategies there were many tests that were failing. This PR rectifies all the tests and also achieves a minimum of 70% code coverage across the project.

fixes #48 
fixes #49

### CODE REVIEW

**Review by yashipro13 — APPROVED** [review]

**Review by djChatt — APPROVED** [review]

File: .gitignore [hunk 1]
```diff
@@ -21,3 +21,4 @@ job_data_example/config/
 cliLogs.txt
 controllerLogs.txt
 executorLogs.txt
+testLogs.txt
```
Comment (faruqisan) [inline .gitignore:24]: for a better convention, logs file should be in `.log` file type such as: 

- controller.log
- executor.log

and also you should put it inside some folder, for example, the logs folder will be in: `/var/log/octavius/controller.log`

this would make our logging following standard UNIX scheme. Can you help refactor this?

File: internal/pkg/log/log.go [hunk 2]
```diff
@@ -29,15 +28,17 @@ func Init(configLogLevel string, logFile string, logInConsole bool) error {
 		return err
 	}
 
+	if logFile == "" {
+		logFile = "./testLogs.txt"
```
Comment (faruqisan) [inline internal/pkg/log/log.go:32]: for a better convention, logs file should be in .log file type such as:

controller.log
executor.log
test.log
and also you should put it inside some folder, for example, the logs folder will be in /var/log/octavius/controller.log

this would make our logging following standard UNIX scheme. Can you help refactor this?

**Review by faruqisan — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 1 above)
Comment (faruqisan) [reply .gitignore:24]: or we can create new folder in `~/.octavius/log/`

File: internal/pkg/log/log.go (hunk 2 above)
Comment (faruqisan) [reply internal/pkg/log/log.go:32]: or we can create new folder in `~/.octavius/log/`

File: .gitignore (hunk 1 above)
Comment (littlestar642) [reply .gitignore]: Sure. Now all the logs are written in ~/.octavius/log/

File: internal/pkg/log/log.go (hunk 2 above)
Comment (littlestar642) [reply internal/pkg/log/log.go]: Sure. Now all the logs are written in ~/.octavius/log/

File: internal/pkg/log/log.go [hunk 3]
```diff
@@ -53,6 +72,29 @@ func Init(configLogLevel string, logFile string, logInConsole bool) error {
 	return nil
 }
 
+func createFile(path string) error {
+	// check if file exists
+	var _, err = os.Stat(path)
```
Comment (faruqisan) [inline internal/pkg/log/log.go:77]: handle other err.
```go
        _, err := os.Stat(path)
	if err != nil {
                // if it's error other than IsNotExist return it
		if !os.IsNotExist(err) {
			return err
		}
		// if err is file is not exist then we create the file
		if err = ioutil.WriteFile(path, []byte(""), 0644); err != nil {
			return err
		}
	}
	return nil
```

File: internal/pkg/log/log.go [hunk 4]
```diff
@@ -53,6 +72,29 @@ func Init(configLogLevel string, logFile string, logInConsole bool) error {
...
+		if err != nil {
+			return err
+		}
+		defer file.Close()
+	}
+	return nil
+}
+
+func createDir(path string) error {
+	var err = os.Mkdir(path, 0755)
```
Comment (faruqisan) [inline internal/pkg/log/log.go:91]: handle other err.
```go
        err := os.Mkdir(path, 0755)
	if err != nil {
		// if it's error IsExist return nil
		if os.IsExist(err) {
			return nil
		}
		return err
	}
	return nil
```

**Review by faruqisan — CHANGES_REQUESTED** [review]

File: .gitignore [hunk 5]
```diff
@@ -18,6 +18,4 @@ job_data_example/config/
 .vscode/
 .idea/
 .DS_Store
-cliLogs.txt
-controllerLogs.txt
-executorLogs.txt
+
```
[the remark this answers is not in the document]
Comment (littlestar642) [reply .gitignore:21]: given we are adding our logs to system's home dir, I guess adding that to gitignore might not be meaningful

[the remark this answers is not in the document]
Comment (faruqisan) [reply .gitignore:21]: I totally forget that sorry.

**Review by faruqisan — APPROVED** [review]
LGTM
