### PR TITLE
fix: Refactor getstream command #87

### LINKED ISSUE #87: fix: Refactor getstream command
#### Description
The getstream command does not require stream functionality of gRPC. So change it to simple response and also rename it to getlogs. 

#### Present Behaviour 
getstream command is using a stream but sending response only a single time.

#### Expected Behaviour
As described above.

### PR DESCRIPTION
**Pull request by adbusa67**
#### Description
This pull request removes unnecessary stream functionality from getstream command and renames command to getlogs. fixes #87 

#### Present Behaviour
getstream command is using a stream but sending a response only a single time.

#### Expected Behaviour
As described above.

### CODE REVIEW

File: internal/cli/command/create/create.go [hunk 1]
```diff
@@ -44,7 +45,7 @@ func NewCmd(octaviusDaemon daemon.Client, fileUtil file.File) *cobra.Command {
 		},
 	}
 	createCmd.Flags().StringVarP(&metadataFilePath, "job-path", "", "", "path to metadata.json(required)")
-	createCmd.MarkFlagRequired("job-path")
+	_ = createCmd.MarkFlagRequired("job-path")
```
Comment (littlestar642) [inline internal/cli/command/create/create.go:48]: it will be better if we not ignore the error returned and rather treat it the way it should be. At all the places.

File: internal/cli/command/execution/execution.go [hunk 2]
```diff
@@ -37,7 +50,13 @@ func NewCmd(octaviusDaemon daemon.Client) *cobra.Command {
 				return
 			}
 			log.Info(response.Status)
-			printer.Println(fmt.Sprintf("Job has been added to pending list successfully.\nYou can see the execution logs using getstream %s", response.Status), color.FgGreen)
+			printer.Println(fmt.Sprintf("Job has been added to pending list successfully.\nYou can see the execution logs using getlogs --job-id %s", response.Status), color.FgGreen)
 		},
 	}
+
+	executionCmd.Flags().StringVarP(&jobName, "job-name", "", "", "It contains Job Name")
+	executionCmd.MarkFlagRequired("job-name")
```
Comment (littlestar642) [inline internal/cli/command/execution/execution.go:58]: treat the error generated accordingly. Should not leave them unhandled

File: internal/cli/command/execution/execution.go [hunk 3]
```diff
@@ -14,21 +15,33 @@ import (
...
-	return &cobra.Command{
+	var jobName string
+	var jobArgs string
+	executionCmd := &cobra.Command{
 		Use:     "execute",
 		Short:   "Execute the existing job",
 		Long:    "This command helps to execute the job which is already created in server",
-		Example: fmt.Sprintf("octavius execute <job-name> arg1=argvalue1 arg2=argvalue2"),
-		Args:    cobra.MinimumNArgs(1),
+		Example: fmt.Sprintf("octavius execute --job-name <job-name> --args arg1=value1,arg2=value2"),
```
Comment (littlestar642) [inline internal/cli/command/execution/execution.go:24]: This looks really good as compared to the previous version. 👍

**Review by littlestar642 — CHANGES_REQUESTED** [review]

**Review by littlestar642 — APPROVED** [review]
