### PR TITLE
fix: Refactor scheduler, job repository and execution #60

### LINKED ISSUE #60: fix: Refactor scheduler, job repository and execution
#### Description
Refactor code of scheduler so that every database related operation should happen in the repository directory. Add jobContext protobuf as the value in database instead of adding the only jobID

#### Present Behaviour
Database operations happens in the scheduler file. only JobID is stored in a database while user executes job.

#### Expected Behaviour
Every database related operation will happen in the repository directory.  jobContext protobuf as the value will be added in database instead of adding the only jobID

### PR DESCRIPTION
**Pull request by darshak-sorathiya**
Description
This pull request refactors the code of scheduler so that every database related operation will happen in the repository directory . Now  jobContext protobuf will be added as the value in the database instead of adding the only jobID while the client executes a job.

fixes #60 

Present Behaviour
Database operations happens in the scheduler file. only JobID is stored in a database while user executes job.

Expected Behaviour
Every database related operation will happen in the repository directory. jobContext protobuf as the value will be added in the database instead of adding the only jobID

### CODE REVIEW

File: internal/controller/server/execution/execution.go [hunk 1]
```diff
@@ -183,27 +182,23 @@ func getActiveExecutorMap(e *execution) *activeExecutorMap {
 	return e.activeExecutorMap
 }
 
-//ExecuteJob function will call job repository and get jobId
-func (e *execution) ExecuteJob(ctx context.Context, jobName string, jobData map[string]string) (uint64, error) {
-	jobAvailabilityStatus, err := e.jobRepo.CheckJobMetadataIsAvailable(ctx, jobName)
+// ExecuteJob function will call job repository and get jobId
+func (e *execution) ExecuteJob(ctx context.Context, jobContext *clientCPproto.RequestForExecute) (uint64, error) {
+	jobAvailabilityStatus, err := e.jobRepo.CheckJobMetadataIsAvailable(ctx, jobContext.JobName)
```
Comment (djChatt) [inline internal/controller/server/execution/execution.go:187]: This operation is more specific to the metadata repository instead of jobRepo. Can you create a Get method in metadata repo and use that for this query instead of doing it through the jobRepo?

File: internal/controller/server/repository/job/job.go [hunk 2]
```diff
@@ -2,67 +2,85 @@ package job
...
 	"strings"
+
+	"github.com/golang/protobuf/proto"
 )
 
-type JobRepository interface {
-	ExecuteJob(context.Context, string, string, map[string]string) error
-	CheckJobMetadataIsAvailable(context.Context, string) (bool, error)
+type Repository interface {
+	CheckJobMetadataIsAvailable(ctx context.Context, jobName string) (bool, error)
```
Comment (djChatt) [inline internal/controller/server/repository/job/job.go:16]: Please move this function to metadata repo interface.

**Review by djChatt — CHANGES_REQUESTED** [review]

**Comment by littlestar642** [comment]
Guys the tests are failing with this message 

```log
case-insensitive import collision: "octavius/internal/pkg/protofiles/client_CP" and "octavius/internal/pkg/protofiles/client_cp"
##[error]Process completed with exit code 1.
```

You need to remove your `octavius/internal/pkg/protofiles/client_CP` and `executor_CP` by using `git rm <path>` and then `git pull` again. This way you will get the folder with lowercase name

File: go.mod [hunk 3]
```diff
@@ -5,6 +5,7 @@ go 1.14
 require (
 	github.com/coreos/etcd v3.3.13+incompatible
 	github.com/fatih/color v1.7.0
+	github.com/gogo/protobuf v1.2.1
```
Comment (littlestar642) [inline go.mod:8]: dony use `gogo/protobuf`. Its unstable for now for marshalling and unmarshalling. Instead use `golang/protobuf`. Remove this import from go mod and also from replace in any of your file with `golang/protobuf`

File: internal/controller/server/client_services.go [hunk 4]
```diff
@@ -84,9 +84,9 @@ func (s *clientCPServicesServer) GetStreamLogs(request *clientCPproto.RequestFor
 	return nil
 }
 
-//ExecuteJob will call Executejob function of execution and get jobId
-func (s *clientCPServicesServer) ExecuteJob(ctx context.Context, execute *clientCPproto.RequestForExecute) (*clientCPproto.Response, error) {
-	jobId, err := s.procExec.ExecuteJob(ctx, execute.JobName, execute.JobData)
+// ExecuteJob will call ExecuteJob function of execution and get jobId
+func (s *clientCPServicesServer) ExecuteJob(ctx context.Context, jobContext *clientCPproto.RequestForExecute) (*clientCPproto.Response, error) {
```
Comment (littlestar642) [inline internal/controller/server/client_services.go:88]: Dont use the name jobContext for arguments we are sending in for executing a job. Use a better name which conveys the meaning simply

File: internal/controller/server/execution/execution_test.go [hunk 5]
```diff
@@ -125,132 +126,121 @@ func TestUpdateExecutorStatus(t *testing.T) {
...
-	jobRepoMock.On("CheckJobMetadataIsAvailable", "testJob").Return(true, nil)
+	testJobID := uint64(12345)
+
+	jobRepoMock.On("CheckJobMetadataIsAvailable", testJobContext.JobName).Return(false, errors.New("failed to check jobMetadata in job repo"))
+	mockRandomIdGenerator.On("Generate").Return(testJobID, nil)
+	mockScheduler.On("AddToPendingList", testJobID, testJobContext).Return(nil)
 
-	jobId, err := testExec.ExecuteJob(context.Background(), "testJob", testJobData)
-	assert.Equal(t, err.Error(), "failed to generate random id")
+	jobId, err := testExec.ExecuteJob(context.Background(), testJobContext)
```
Comment (littlestar642) [inline internal/controller/server/execution/execution_test.go:210]: can you please replace all the uses of Id with ID where ever needed

**Review by littlestar642 — CHANGES_REQUESTED** [review]

File: internal/controller/server/repository/job/job.go [hunk 6]
```diff
@@ -2,67 +2,85 @@ package job
...
-		return err
-	}
+	return true, nil
+}
 
-	err = storeEnvVariablesInDatabase(ctx, j.etcdClient, jobIdString, jobData)
+// Save takes jobID and jobContext and save it in database as pendingList
+func (j jobRepository) Save(ctx context.Context, jobID uint64, jobContext *clientCPproto.RequestForExecute) error {
+	jobIDasString := strconv.FormatUint(jobID, 10)
+	key := "jobs/pending/" + jobIDasString
```
Comment (djChatt) [inline internal/controller/server/repository/job/job.go:53]: use the constant declared above instead of writing out the prefix

**Review by djChatt — CHANGES_REQUESTED** [review]

File: internal/controller/server/execution/execution.go (hunk 1 above)
Comment (darshak-sorathiya) [reply internal/controller/server/execution/execution.go:187]: Actually, That function is not metadata related.It is job Related. we will change checkjobMetadataIsAvailable to checkJobAvailable.

File: internal/controller/server/repository/job/job.go (hunk 6 above)
Comment (darshak-sorathiya) [reply internal/controller/server/repository/job/job.go:53]: Sure

File: internal/controller/server/client_services.go [hunk 7]
```diff
@@ -84,9 +84,9 @@ func (s *clientCPServicesServer) GetStreamLogs(request *clientCPproto.RequestFor
 	return nil
 }
 
-//ExecuteJob will call Executejob function of execution and get jobId
-func (s *clientCPServicesServer) ExecuteJob(ctx context.Context, execute *clientCPproto.RequestForExecute) (*clientCPproto.Response, error) {
-	jobId, err := s.procExec.ExecuteJob(ctx, execute.JobName, execute.JobData)
+// ExecuteJob will call ExecuteJob function of execution and get jobId
+func (s *clientCPServicesServer) ExecuteJob(ctx context.Context, executionContext *clientCPproto.RequestForExecute) (*clientCPproto.Response, error) {
```
Comment (littlestar642) [inline internal/controller/server/client_services.go:88]: Dont use the name *Context with requestForExecute as context has a very different meaning in golang. I would suggest using a name like request, executionVars, etc

File: internal/controller/server/repository/job/job.go [hunk 8]
```diff
@@ -2,67 +2,85 @@ package job
...
+	jobIDasString := strconv.FormatUint(jobID, 10)
+	key := pendingPrefix + jobIDasString
+	value, err := proto.Marshal(executionContext)
 	if err != nil {
 		return err
 	}
-
-	return nil
+	valueAsString := string(value)
+	return j.etcdClient.PutValue(ctx, key, valueAsString)
```
Comment (littlestar642) [inline internal/controller/server/repository/job/job.go:59]: I guess you can reduce both these to one line

**Review by littlestar642 — CHANGES_REQUESTED** [review]
Also git rm your client_CP and executor_CP folders

File: internal/controller/server/client_services.go (hunk 7 above)
Comment (JaiminRathod) [reply internal/controller/server/client_services.go:88]: It contains all execution-related things like job name, arguments, and some other info, so we gave this structure name as executionContext in all files.

File: internal/controller/server/repository/job/job.go (hunk 8 above)
Comment (JaiminRathod) [reply internal/controller/server/repository/job/job.go:59]: I think it's not good practice to do two operations in one line

Comment (littlestar642) [reply internal/controller/server/repository/job/job.go:62]: its not a good practice to initialise methods inline but we should not be creating redundant variables just to use them in the next line. I guess you should remove this

File: internal/controller/server/client_services.go (hunk 7 above)
Comment (littlestar642) [reply internal/controller/server/client_services.go:88]: I guess its not good to use this name. Please use a different name for this variable

File: internal/controller/server/repository/job/job.go [hunk 9]
```diff
@@ -2,67 +2,87 @@ package job
...
-		key := "jobs/" + jobId + "/env/" + envName
-		err := etcdClient.PutValue(ctx, key, value)
-		if err != nil {
-			return err
+// CheckJobIsAvailable returns true if given job is available otherwise returns false
+func (j jobRepository) CheckJobIsAvailable(ctx context.Context, jobName string) (bool, error) {
+	_, err := j.etcdClient.GetValue(ctx, "metadata/"+jobName)
+	if err != nil {
+		if err.Error() == constant.NoValueFound {
+			return false, errors.New("job with given name not found")
```
Comment (faruqisan) [inline internal/controller/server/repository/job/job.go:43]: add more context to error message, like what is the name that not found.

File: internal/controller/server/repository/job/job.go [hunk 10]
```diff
@@ -2,67 +2,87 @@ package job
...
+		} else {
```
Comment (faruqisan) [inline internal/controller/server/repository/job/job.go:44]: if the above line already has return, this else conditional is no longer require you can put `return false, err` here

File: internal/controller/server/repository/job/job.go [hunk 11]
```diff
@@ -2,67 +2,87 @@ package job
...
+	return true, nil
 }
 
-func (j jobRepository) ExecuteJob(ctx context.Context, jobIdString string, jobName string, jobData map[string]string) error {
-	key := "jobs/" + jobIdString + "/metadataKeyName"
-	value := "metadata/" + jobName
-	err := j.etcdClient.PutValue(ctx, key, value)
+// Save takes jobID and executionContext and save it in database as pendingList
+func (j jobRepository) Save(ctx context.Context, jobID uint64, executionContext *clientCPproto.RequestForExecute) error {
+	jobIDasString := strconv.FormatUint(jobID, 10)
```
Comment (faruqisan) [inline internal/controller/server/repository/job/job.go:53]: this is not required because if you want to use it as a string in the key variable you can directly format there.

File: internal/controller/server/repository/job/job.go [hunk 12]
```diff
@@ -2,67 +2,87 @@ package job
...
+	key := pendingPrefix + jobIDasString
```
Comment (faruqisan) [inline internal/controller/server/repository/job/job.go:54]:
```go
key := pendingPrefix + strconv.FormatUint(jobID, 10)
```
or use fmt.Sprintf
```go
key := fmt.Sprintf("%s%d", pendingPrefix, jobID)
```

File: internal/controller/server/repository/job/job.go [hunk 13]
```diff
@@ -2,67 +2,87 @@ package job
...
 	}
+	valueAsString := string(value)
 
-	err = storeEnvVariablesInDatabase(ctx, j.etcdClient, jobIdString, jobData)
-	if err != nil {
-		return err
-	}
-
-	return nil
+	log.Info(fmt.Sprintf("Request ID: %v, saving executionContext to etcd with value %v", ctx.Value(util.ContextKeyUUID), executionContext))
```
Comment (faruqisan) [inline internal/controller/server/repository/job/job.go:61]: change second `%v` to `%+v` so the field name printed

**Review by faruqisan — CHANGES_REQUESTED** [review]

File: internal/controller/server/client_services.go (hunk 7 above)
Comment (darshak-sorathiya) [reply internal/controller/server/client_services.go:88]: we have changed it to executionData

File: internal/controller/server/repository/job/job.go (hunk 10 above)
Comment (darshak-sorathiya) [reply internal/controller/server/repository/job/job.go:44]: If we directly pass the err: "No value found" to user, then the user can't understand its meaning. so for clarification of error, we have made a custom err "job with particular jobname is not found". for this purpose, we have used a conditional statement.

Comment (faruqisan) [reply internal/controller/server/repository/job/job.go:44]: I just simply ask you to restructure the error handling not what error to return to user

to add more context this is what I want it to looks like

```go
	if err != nil {
		if err.Error() == constant.NoValueFound {
			return false, errors.New("job with given name not found")
		}
                return false, err
	}
```

My point is you don't need to add `else {}` because in 

```go
if err.Error() == constant.NoValueFound {
  return false, errors.New("job with given name not found")
}
```
it already has return.

Comment (darshak-sorathiya) [reply internal/controller/server/repository/job/job.go:44]: Okay, got it.

**Review by faruqisan — APPROVED** [review]
LGTM

**Review by littlestar642 — APPROVED** [review]
