### PR TITLE
fix: Add validation of metadata during job creation

### LINKED ISSUE #89: fix: Add validation of metadata during job creation
#### Description
Now we are not doing validation of metadata during job creation, so it must be done.

#### Present behaviour
No such behaviour.

#### Exepected behaviour
There should be functionality of metadata validation during job creation.

### PR DESCRIPTION
**Pull request by JaiminRathod**
#### Description
This pull request implements the validation of metadata during job creation time. fixes #89 

#### Present behaviour
No such behaviour.

#### Exepected behaviour
There should be a functionality of metadata validation during job creation.

### CODE REVIEW

File: internal/cli/command/create/create.go [hunk 1]
```diff
@@ -37,6 +37,7 @@ func NewCmd(octaviusDaemon daemon.Client, fileUtil file.File) *cobra.Command {
 			client := &client.GrpcClient{}
 			res, err := octaviusDaemon.CreateMetadata(metadataFileIoReader, client)
 			if err != nil {
+				fmt.Println(err)
```
Comment (littlestar642) [inline internal/cli/command/create/create.go:40]: Why do we need this here?

File: internal/cli/daemon/client.go [hunk 2]
```diff
@@ -55,13 +57,60 @@ func (c *octaviusClient) startOctaviusClient(grpcClient client.Client) error {
 	return nil
 }
 
+func validateImageName(imageName string) (bool, error) {
```
Comment (littlestar642) [inline internal/cli/daemon/client.go:60]: I would suggest that we rename this to validateImageNameDocker to signify that in this function we validate for the image to be in docker registry. Later if we add a private registry we can just add a different local function and plug that where needed.

File: internal/cli/daemon/client.go [hunk 3]
```diff
@@ -55,13 +57,60 @@ func (c *octaviusClient) startOctaviusClient(grpcClient client.Client) error {
...
+		url = "https://hub.docker.com/v2/repositories/" + imageNameWithoutTag + "/tags/" + tag
+	} else {
+		return false, status.Error(codes.Internal, "invalid image name")
+	}
+
+	response, err := http.Get(url)
+	if err != nil {
+		return false, status.Error(codes.Internal, "error in validating image name")
+	}
+	if response.StatusCode == 200 {
```
Comment (littlestar642) [inline internal/cli/daemon/client.go:87]: do we get a StatusCode 404 in case when the image is not present in registry? Can we track that and tell the user if image is not found?

File: internal/cli/daemon/client.go [hunk 4]
```diff
@@ -55,13 +57,60 @@ func (c *octaviusClient) startOctaviusClient(grpcClient client.Client) error {
...
 	metadata := protobuf.Metadata{}
 	err := jsonpb.Unmarshal(metadataFileHandler, &metadata)
 	if err != nil {
 		return nil, status.Error(codes.Internal, err.Error())
 	}
+	if metadata.Name == "" {
+		return nil, status.Error(codes.Internal, "job-name should not be empty in metadata")
+	}
+
+	doesExist, err := validateImageName(metadata.ImageName)
```
Comment (littlestar642) [inline internal/cli/daemon/client.go:104]: please use a better username as compared to doesExist

**Review by littlestar642 — CHANGES_REQUESTED** [review]

File: internal/cli/daemon/client.go (hunk 3 above)
Comment (JaiminRathod) [reply internal/cli/daemon/client.go:87]: yes

**Review by littlestar642 — APPROVED** [review]
