### PR TITLE
fix: Add error support to config files #65

### LINKED ISSUE #65: fix: handle errors from all the config files
Description:

The config files generate error but they are not being handled as needed. There are also some lint errors in the present project that needs to be rectified.

Present Behavior:

The config files do not handle errors

Expected Behavior:

The config files should handle and return errors

### PR DESCRIPTION
**Pull request by littlestar642**
Description:

The config files now returns errors which can be logged in the main caller. This has been implemented in all the three config files present

fixes #65

### CODE REVIEW

File: internal/controller/server/execution/execution_test.go [hunk 1]
```diff
@@ -114,13 +115,13 @@ func TestUpdateExecutorStatus(t *testing.T) {
...
 	executorRepoMock.On("UpdateStatus", "exec 1", "free").Return(nil)
-	res, err := testExec.UpdateExecutorStatus(ctx, &request)
+	res, err := testExec.UpdateExecutorStatus(ctx, &request, 20*time.Second)
 	_, ok := getActiveExecutorMap(testExec.(*execution)).Get("exec 1")
 	assert.Equal(t, res.Recieved, true)
 	assert.Nil(t, err)
 	assert.Equal(t, true, ok)
-
-	res, err = testExec.UpdateExecutorStatus(ctx, &request)
+	pingTimeOut := 20 * time.Second
```
Comment (yashipro13) [inline internal/controller/server/execution/execution_test.go:123]: can we move this 20 to constants, looking like a magic variable, and is being used at plenty of places.

Comment (littlestar642) [reply internal/controller/server/execution/execution_test.go:123]: this is a test file variable. I am not sure if we should add a constant here. Also this is mostly testbased stuff
